# ABC Foodmart ETL

The goal of this ETL:
- extract generated CSV files
- transform into clean and analysis-ready tables
- load them them into PostgreSQL
- validate the loaded data with SQL

We follow these concepts include:
- Python + PostgreSQL connection with `psycopg2`
- pandas for data handling
- ETL as extract, transform, and load
- validation after loading
- normalized relational design with keys and constraints

In [129]:
# install packages if needed
# run this only one time in our environment

# !pip install pandas sqlalchemy psycopg2-binary jupyter

In [1]:
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine, text
import numpy as np

## Set paths and database connection

In [2]:
# path to our generated csv files
DATA_DIR = Path.home() / "Desktop" / "abc_foodmart_fake_data"

# PostgreSQL setup
DB_USER = "postgres"
DB_PASSWORD = "123"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "abc_foodmart"

CONN_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

print(DATA_DIR)
print(CONN_URL.replace(DB_PASSWORD, "****"))

/Users/plypye/Desktop/abc_foodmart_fake_data
postgresql://postgres:****@localhost:5432/abc_foodmart

In [3]:
# create database engine
engine = create_engine(CONN_URL)

## 1. Extract step

ETL process:
- Extract -> get data from a source
- Transform -> clean and reshape
- Load -> send data to a database or analysis

In [4]:
TABLE_FILES = [
    "store",
    "department",
    "product_category",
    "product",
    "vendor",
    "vendor_product",
    "customer",
    "customer_loyalty_account",
    "employee",
    "store_department",
    "inventory",
    "purchase_order",
    "purchase_order_line",
    "delivery",
    "sales_transaction",
    "sales_transaction_line",
    "payment",
    "shift_schedule",
    "payroll_record",
    "accounting_record",
]

tables = {}
for name in TABLE_FILES:
    file_path = DATA_DIR / f"{name}.csv"
    tables[name] = pd.read_csv(file_path)

print("Loaded tables:", list(tables.keys()))

Loaded tables: ['store', 'department', 'product_category', 'product', 'vendor', 'vendor_product', 'customer', 'customer_loyalty_account', 'employee', 'store_department', 'inventory', 'purchase_order', 'purchase_order_line', 'delivery', 'sales_transaction', 'sales_transaction_line', 'payment', 'shift_schedule', 'payroll_record', 'accounting_record']

In [5]:
# quick preview
for name in ["store", "employee", "product", "sales_transaction", "sales_transaction_line"]:
    print("\n" + "=" * 60)
    print(name)
    display(tables[name].head())

============================================================
store

,store_id,store_name,borough,street_address,phone_number,open_date,store_status
0,1,ABC Foodmart Q1,Queens,"12-01 Astoria Blvd, Astoria, Queens, NY",718-555-2824,2020-02-15,open
1,2,ABC Foodmart Q2,Queens,"44-15 Queens Blvd, Sunnyside, Queens, NY",718-555-1409,2020-08-20,open
2,3,ABC Foodmart B3,Brooklyn,"212 Bedford Ave, Brooklyn, NY",718-555-5506,2025-01-15,open
3,4,ABC Foodmart B4,Brooklyn,"305 Court St, Brooklyn, NY",718-555-5012,2025-04-10,open
4,5,ABC Foodmart B5,Brooklyn,"7813 5th Ave, Brooklyn, NY",718-555-4657,2025-07-01,open

============================================================
employee

,employee_id,store_id,department_id,first_name,last_name,email_address,phone_number,hire_date,employment_status,job_title,hourly_rate,annual_salary
0,1,1,2,Sandra,Cunningham,sandra.cunningham.1@abcfoodmart.com,718-555-8933,2025-05-01,active,Store Manager,NaN,98188.16
1,2,1,5,Cynthia,Weber,cynthia.weber.2@abcfoodmart.com,718-555-6231,2023-12-30,leave,Assistant Manager,NaN,67873.37
2,3,1,6,Michelle,Burton,michelle.burton.3@abcfoodmart.com,718-555-7070,2021-04-24,active,Department Manager,NaN,54615.32
3,4,1,4,Edward,Jones,edward.jones.4@abcfoodmart.com,718-555-5382,2025-03-01,active,Department Manager,NaN,61329.45
4,5,1,3,Scott,Turner,scott.turner.5@abcfoodmart.com,718-555-5754,2024-06-06,inactive,Department Manager,NaN,53936.23

============================================================
product

,product_id,category_id,product_name,brand_name,package_size,unit_of_measure,barcode,is_perishable,product_status,current_unit_price
0,1,1,Brooklyn Best Potatoes,Brooklyn Best,5 lb,bag,889984729564,True,seasonal,6.24
1,2,2,Brooklyn Best Mozzarella,Brooklyn Best,8 oz,pack,599263022595,True,active,3.76
2,3,3,Pure Living Ribeye Steak,Pure Living,2 lb,lb,400947542743,True,active,34.33
3,4,4,Pure Living Chocolate Cake,Pure Living,single,each,409248663017,True,seasonal,14.05
4,5,5,Queens Choice French Fries,Queens Choice,32 oz,bag,480037352466,True,active,5.90

============================================================
sales_transaction

,sale_id,store_id,customer_id,employee_id,sale_timestamp,sales_subtotal,discount_total,tax_total,points_earned,points_redeemed,total_amount
0,1,2,75.0,29,2025-04-19 18:07:00,47.60,0.0,4.22,47,10,51.72
1,2,1,63.0,1,2025-04-26 15:22:00,61.69,0.0,5.47,61,0,67.16
2,3,5,NaN,61,2025-11-29 16:09:00,12.12,0.0,1.08,0,0,13.20
3,4,5,NaN,72,2025-11-15 11:37:00,29.63,0.0,2.63,0,0,32.26
4,5,5,NaN,72,2025-08-25 09:51:00,23.83,0.0,2.11,0,0,25.94

============================================================
sales_transaction_line

,sale_line_id,sale_id,product_id,quantity_sold,unit_price,discount_amount,line_total
0,1,1,76,3,3.14,0.0,9.42
1,2,1,49,3,1.02,0.0,3.06
2,3,1,111,2,17.56,0.0,35.12
3,4,2,35,2,5.66,0.0,11.32
4,5,2,148,5,9.52,0.0,47.60

In [6]:
# row counts
row_counts = pd.DataFrame({
    "table_name": list(tables.keys()),
    "row_count": [len(df) for df in tables.values()]
}).sort_values("table_name")

row_counts

                  table_name  row_count
19         accounting_record       1100
6                   customer        200
7   customer_loyalty_account        160
13                  delivery         90
1                 department          7
8                   employee         75
10                 inventory        750
16                   payment       1000
18            payroll_record        150
3                    product        150
2           product_category         12
11            purchase_order        100
12       purchase_order_line        300
14         sales_transaction       1000
15    sales_transaction_line       3000
17            shift_schedule        450
0                      store          5
9           store_department         35
4                     vendor         20
5             vendor_product        250

## 2. Transform step

- standardize date and time columns
- check duplicates and nulls
- check primary keys and foreign keys
- check business rules
- create a few analysis-ready fields

### 2.1 Convert date and time fields + Standardize ID data types

In [21]:
date_cols = {
    "store": ["open_date"],
    "customer": ["join_date"],
    "employee": ["hire_date"],
    "inventory": ["last_updated_at"],
    "purchase_order": ["purchase_order_date", "expected_delivery_date"],
    "delivery": ["delivery_date"],
    "sales_transaction": ["sale_timestamp"],
    "payment": ["payment_timestamp"],
    "shift_schedule": ["shift_start_date", "shift_end_date", "clock_in_time", "clock_out_time"],
    "payroll_record": ["period_start_date", "period_end_date", "pay_date"],
    "customer_loyalty_account": ["created_at"],
    "accounting_record": ["record_date"],
}

# Convert date/time columns
for table_name, cols in date_cols.items():
    for col in cols:
        if col in tables[table_name].columns:
            tables[table_name][col] = pd.to_datetime(tables[table_name][col], errors="coerce")

print("Date conversion done.")

# Standardize ID data types (nullable foreign keys that may have been read as float)
id_type_conversions = {
    "accounting_record": ["sale_id", "purchase_order_id"],
    "sales_transaction": ["customer_id"],
    "delivery": ["received_by_employee_id"],
    "store_department": ["department_manager_id"],
}

for table_name, id_cols in id_type_conversions.items():
    for col in id_cols:
        if col in tables[table_name].columns:
            # Convert to Int64 (nullable integer type)
            tables[table_name][col] = tables[table_name][col].astype('Int64')

print("ID type standardization done.")

Date conversion done.
ID type standardization done.

### 2.2 Check duplicates and missing values

In [22]:
null_summary = []
dup_summary = []

for name, df in tables.items():
    null_pct = (df.isnull().mean() * 100).round(2)
    for col, pct in null_pct.items():
        if pct > 0:
            null_summary.append({
                "table_name": name,
                "column_name": col,
                "null_pct": pct
            })

    dup_summary.append({
        "table_name": name,
        "duplicate_rows": int(df.duplicated().sum())
    })

null_summary_df = pd.DataFrame(null_summary).sort_values(["table_name", "null_pct"], ascending=[True, False])
dup_summary_df = pd.DataFrame(dup_summary).sort_values("table_name")

display(dup_summary_df)
display(null_summary_df.head(30))

                  table_name  duplicate_rows
19         accounting_record               0
6                   customer               0
7   customer_loyalty_account               0
13                  delivery               0
1                 department               0
8                   employee               0
10                 inventory               0
16                   payment               0
18            payroll_record               0
3                    product               0
2           product_category               0
11            purchase_order               0
12       purchase_order_line               0
14         sales_transaction               0
15    sales_transaction_line               0
17            shift_schedule               0
0                      store               0
9           store_department               0
4                     vendor               0
5             vendor_product               0

           table_name              column_name  null_pct
13  accounting_record        purchase_order_id     94.45
12  accounting_record                  sale_id      9.09
0            customer             phone_number     17.50
6            delivery             delay_reason     40.00
3            delivery  received_by_employee_id     32.22
4            delivery            delivery_date     32.22
5            delivery               delay_days     32.22
1            employee              hourly_rate     60.00
2            employee            annual_salary     40.00
8             payment        confirmation_code     19.00
11     payroll_record             hours_worked     60.00
7   sales_transaction              customer_id     29.70
9      shift_schedule            clock_in_time     11.56
10     shift_schedule           clock_out_time     11.56

### 2.3 Primary key checks

In [23]:
pk_map = {
    "store": ["store_id"],
    "department": ["department_id"],
    "product_category": ["category_id"],
    "product": ["product_id"],
    "vendor": ["vendor_id"],
    "customer": ["customer_id"],
    "customer_loyalty_account": ["loyalty_account_id"],
    "employee": ["employee_id"],
    "inventory": ["inventory_id"],
    "purchase_order": ["purchase_order_id"],
    "purchase_order_line": ["purchase_order_line_id"],
    "delivery": ["delivery_id"],
    "sales_transaction": ["sale_id"],
    "sales_transaction_line": ["sale_line_id"],
    "payment": ["payment_id"],
    "shift_schedule": ["shift_id"],
    "payroll_record": ["payroll_id"],
    "accounting_record": ["accounting_record_id"],
    "vendor_product": ["vendor_id", "product_id"],
    "store_department": ["store_id", "department_id"],
}

pk_results = []
for table_name, cols in pk_map.items():
    df = tables[table_name]
    pk_results.append({
        "table_name": table_name,
        "pk_columns": ", ".join(cols),
        "duplicate_pk_rows": int(df.duplicated(subset=cols).sum()),
        "null_pk_values": int(df[cols].isnull().sum().sum())
    })

pk_results_df = pd.DataFrame(pk_results).sort_values("table_name")
pk_results_df

,table_name,pk_columns,duplicate_pk_rows,null_pk_values
17,accounting_record,accounting_record_id,0,0
5,customer,customer_id,0,0
6,customer_loyalty_account,loyalty_account_id,0,0
11,delivery,delivery_id,0,0
1,department,department_id,0,0
7,employee,employee_id,0,0
8,inventory,inventory_id,0,0
14,payment,payment_id,0,0
16,payroll_record,payroll_id,0,0
3,product,product_id,0,0
2,product_category,category_id,0,0
9,purchase_order,purchase_order_id,0,0
10,purchase_order_line,purchase_order_line_id,0,0
12,sales_transaction,sale_id,0,0
13,sales_transaction_line,sale_line_id,0,0
15,shift_schedule,shift_id,0,0
0,store,store_id,0,0
19,store_department,"store_id, department_id",0,0
4,vendor,vendor_id,0,0
18,vendor_product,"vendor_id, product_id",0,0

### 2.4 Foreign key checks
We allow nulls in foreign keys where business logic says null is valid.
For example:
- anonymous sales can have null customer_id
- revenue accounting rows can have null purchase_order_id
- expense accounting rows can have null sale_id
- cancelled deliveries can have null received_by_employee_id

In [24]:
fk_checks = [
    ("product", "category_id", "product_category", "category_id", False),
    ("employee", "store_id", "store", "store_id", False),
    ("employee", "department_id", "department", "department_id", False),
    ("customer_loyalty_account", "customer_id", "customer", "customer_id", False),
    ("inventory", "store_id", "store", "store_id", False),
    ("inventory", "product_id", "product", "product_id", False),
    ("vendor_product", "vendor_id", "vendor", "vendor_id", False),
    ("vendor_product", "product_id", "product", "product_id", False),
    ("store_department", "store_id", "store", "store_id", False),
    ("store_department", "department_id", "department", "department_id", False),
    ("store_department", "department_manager_id", "employee", "employee_id", True),
    ("purchase_order", "store_id", "store", "store_id", False),
    ("purchase_order", "vendor_id", "vendor", "vendor_id", False),
    ("purchase_order", "created_by_employee_id", "employee", "employee_id", False),
    ("purchase_order_line", "purchase_order_id", "purchase_order", "purchase_order_id", False),
    ("purchase_order_line", "product_id", "product", "product_id", False),
    ("delivery", "purchase_order_id", "purchase_order", "purchase_order_id", False),
    ("delivery", "vendor_id", "vendor", "vendor_id", False),
    ("delivery", "store_id", "store", "store_id", False),
    ("delivery", "received_by_employee_id", "employee", "employee_id", True),
    ("sales_transaction", "store_id", "store", "store_id", False),
    ("sales_transaction", "customer_id", "customer", "customer_id", True),
    ("sales_transaction", "employee_id", "employee", "employee_id", False),
    ("sales_transaction_line", "sale_id", "sales_transaction", "sale_id", False),
    ("sales_transaction_line", "product_id", "product", "product_id", False),
    ("payment", "sale_id", "sales_transaction", "sale_id", False),
    ("shift_schedule", "employee_id", "employee", "employee_id", False),
    ("shift_schedule", "store_id", "store", "store_id", False),
    ("shift_schedule", "department_id", "department", "department_id", False),
    ("payroll_record", "employee_id", "employee", "employee_id", False),
    ("payroll_record", "store_id", "store", "store_id", False),
    ("accounting_record", "store_id", "store", "store_id", False),
    ("accounting_record", "sale_id", "sales_transaction", "sale_id", True),
    ("accounting_record", "purchase_order_id", "purchase_order", "purchase_order_id", True),
]

fk_results = []

for child, fk, parent, pk, nullable in fk_checks:
    child_df = tables[child]
    parent_df = tables[parent]
    
    # Build set of valid parent IDs (as strings, excluding NULLs)
    valid_values = set(
        parent_df[pk]
        .dropna()
        .astype(str)
        .str.strip()
    )
    
    # Count NULLs in child FK column
    null_count = child_df[fk].isna().sum()
    
    # For validation: check non-NULL values only
    # Use .notna() mask BEFORE converting to string to avoid string "nan" issue
    non_null_mask = child_df[fk].notna()
    values_to_check = (
        child_df.loc[non_null_mask, fk]
        .astype(str)
        .str.strip()
    )
    
    # Count how many non-NULL values are NOT in parent table
    invalid = (~values_to_check.isin(valid_values)).sum()
    
    fk_results.append({
        "child_table": child,
        "fk_column": fk,
        "parent_table": parent,
        "parent_pk": pk,
        "nullable_fk": nullable,
        "null_count": int(null_count),
        "invalid_values": int(invalid)
    })

fk_results_df = pd.DataFrame(fk_results).sort_values(["child_table", "fk_column"])
fk_results_df

,child_table,fk_column,parent_table,parent_pk,nullable_fk,null_count,invalid_values
33,accounting_record,purchase_order_id,purchase_order,purchase_order_id,True,1039,0
32,accounting_record,sale_id,sales_transaction,sale_id,True,100,0
31,accounting_record,store_id,store,store_id,False,0,0
3,customer_loyalty_account,customer_id,customer,customer_id,False,0,0
16,delivery,purchase_order_id,purchase_order,purchase_order_id,False,0,0
19,delivery,received_by_employee_id,employee,employee_id,True,29,0
18,delivery,store_id,store,store_id,False,0,0
17,delivery,vendor_id,vendor,vendor_id,False,0,0
2,employee,department_id,department,department_id,False,0,0
1,employee,store_id,store,store_id,False,0,0
5,inventory,product_id,product,product_id,False,0,0
4,inventory,store_id,store,store_id,False,0,0
25,payment,sale_id,sales_transaction,sale_id,False,0,0
29,payroll_record,employee_id,employee,employee_id,False,0,0
30,payroll_record,store_id,store,store_id,False,0,0
0,product,category_id,product_category,category_id,False,0,0
13,purchase_order,created_by_employee_id,employee,employee_id,False,0,0
11,purchase_order,store_id,store,store_id,False,0,0
12,purchase_order,vendor_id,vendor,vendor_id,False,0,0
15,purchase_order_line,product_id,product,product_id,False,0,0
14,purchase_order_line,purchase_order_id,purchase_order,purchase_order_id,False,0,0
21,sales_transaction,customer_id,customer,customer_id,True,297,0
22,sales_transaction,employee_id,employee,employee_id,False,0,0
20,sales_transaction,store_id,store,store_id,False,0,0
24,sales_transaction_line,product_id,product,product_id,False,0,0
23,sales_transaction_line,sale_id,sales_transaction,sale_id,False,0,0
28,shift_schedule,department_id,department,department_id,False,0,0
26,shift_schedule,employee_id,employee,employee_id,False,0,0
27,shift_schedule,store_id,store,store_id,False,0,0
9,store_department,department_id,department,department_id,False,0,0
10,store_department,department_manager_id,employee,employee_id,True,0,0
8,store_department,store_id,store,store_id,False,0,0
7,vendor_product,product_id,product,product_id,False,0,0
6,vendor_product,vendor_id,vendor,vendor_id,False,0,0

### 2.5 Business rule checks
These checks directly follow our project data plan:
- store must open before employees are hired
- purchase must happen before delivery
- payroll dates must be in order
- sales totals must match line totals
- loyalty status must match last purchase timing
- inventory logic must make sense

In [25]:
# store open date before employee hire date
store_open = tables["store"].set_index("store_id")["open_date"].to_dict()
employee_date_issue = tables["employee"].apply(
    lambda r: r["hire_date"] < store_open[r["store_id"]],
    axis=1
).sum()

# purchase order before delivery
delivery_join = tables["delivery"].merge(
    tables["purchase_order"][["purchase_order_id", "purchase_order_date"]],
    on="purchase_order_id",
    how="left"
)
delivery_date_issue = (
    delivery_join["delivery_date"].notna() &
    (delivery_join["delivery_date"] < delivery_join["purchase_order_date"])
).sum()

# payroll order
payroll = tables["payroll_record"]
payroll_date_issue = (
    (payroll["period_start_date"] >= payroll["period_end_date"]) |
    (payroll["period_end_date"] >= payroll["pay_date"])
).sum()

# sales line logic
sales_line = tables["sales_transaction_line"].copy()
sales_line["calc_line_total"] = (sales_line["unit_price"] * sales_line["quantity_sold"] - sales_line["discount_amount"]).round(2)
sales_line_issue = (sales_line["calc_line_total"] != sales_line["line_total"].round(2)).sum()

# sales subtotal logic
sales = tables["sales_transaction"].copy().set_index("sale_id")
sales_line["gross_line_amount"] = (
    sales_line["unit_price"] * sales_line["quantity_sold"]
).round(2)
gross_sum = sales_line.groupby("sale_id")["gross_line_amount"].sum().round(2)
common_sales = sales.index.intersection(gross_sum.index)
sales_subtotal_issue = (
    gross_sum.loc[common_sales] != sales.loc[common_sales, "sales_subtotal"].round(2)
).sum()

# payroll net pay logic
payroll_net_issue = ((payroll["gross_pay"] - payroll["deduction_amount"]).round(2) != payroll["net_pay"].round(2)).sum()

business_rule_results = pd.DataFrame([
    {"check_name": "employee hire after store open", "issue_count": int(employee_date_issue)},
    {"check_name": "delivery after purchase order", "issue_count": int(delivery_date_issue)},
    {"check_name": "payroll date order", "issue_count": int(payroll_date_issue)},
    {"check_name": "sales line total logic", "issue_count": int(sales_line_issue)},
    {"check_name": "sales subtotal logic", "issue_count": int(sales_subtotal_issue)},
    {"check_name": "payroll net pay logic", "issue_count": int(payroll_net_issue)},
])

business_rule_results

                       check_name  issue_count
0  employee hire after store open            0
1   delivery after purchase order            0
2              payroll date order            0
3          sales line total logic            0
4            sales subtotal logic            0
5           payroll net pay logic            0

### 2.6 Create analysis-ready fields
This is a practical ETL step for dashboards and BI.

We create:
- month
- weekday
- hour
- borough link to sales
- category link to sales line

In [26]:
sales_analysis = tables["sales_transaction"].copy()
sales_analysis["sale_month"] = sales_analysis["sale_timestamp"].dt.to_period("M").astype(str)
sales_analysis["sale_weekday"] = sales_analysis["sale_timestamp"].dt.day_name()
sales_analysis["sale_hour"] = sales_analysis["sale_timestamp"].dt.hour

sales_analysis = sales_analysis.merge(
    tables["store"][["store_id", "borough"]],
    on="store_id",
    how="left"
)

category_lookup = tables["product"][["product_id", "category_id"]].merge(
    tables["product_category"],
    on="category_id",
    how="left"
)

sales_line_analysis = tables["sales_transaction_line"].merge(
    category_lookup[["product_id", "category_name"]],
    on="product_id",
    how="left"
)

display(sales_analysis.head())
display(sales_line_analysis.head())

,sale_id,store_id,customer_id,employee_id,sale_timestamp,sales_subtotal,discount_total,tax_total,points_earned,points_redeemed,total_amount,sale_month,sale_weekday,sale_hour,borough
0,1,2,75,29,2025-04-19 18:07:00,47.60,0.0,4.22,47,10,51.72,2025-04,Saturday,18,Queens
1,2,1,63,1,2025-04-26 15:22:00,61.69,0.0,5.47,61,0,67.16,2025-04,Saturday,15,Queens
2,3,5,<NA>,61,2025-11-29 16:09:00,12.12,0.0,1.08,0,0,13.20,2025-11,Saturday,16,Brooklyn
3,4,5,<NA>,72,2025-11-15 11:37:00,29.63,0.0,2.63,0,0,32.26,2025-11,Saturday,11,Brooklyn
4,5,5,<NA>,72,2025-08-25 09:51:00,23.83,0.0,2.11,0,0,25.94,2025-08,Monday,9,Brooklyn

,sale_line_id,sale_id,product_id,quantity_sold,unit_price,discount_amount,line_total,category_name
0,1,1,76,3,3.14,0.0,9.42,Bakery
1,2,1,49,3,1.02,0.0,3.06,Produce
2,3,1,111,2,17.56,0.0,35.12,Meat
3,4,2,35,2,5.66,0.0,11.32,Household
4,5,2,148,5,9.52,0.0,47.60,Bakery

### 2.7 Quick analyst summaries before load
These summaries help confirm that the transformed data has useful variation for later SQL and Metabase work.

In [27]:
revenue_by_store = sales_analysis.groupby(["store_id", "borough"])["total_amount"].sum().reset_index().sort_values("total_amount", ascending=False)
sales_by_weekday = sales_analysis.groupby("sale_weekday")["sale_id"].count().reset_index().sort_values("sale_id", ascending=False)
sales_by_hour = sales_analysis.groupby("sale_hour")["sale_id"].count().reset_index().sort_values("sale_hour")
qty_by_category = sales_line_analysis.groupby("category_name")["quantity_sold"].sum().reset_index().sort_values("quantity_sold", ascending=False)

display(revenue_by_store)
display(sales_by_weekday)
display(sales_by_hour)
display(qty_by_category)

   store_id   borough  total_amount
4         5  Brooklyn       7695.18
3         4  Brooklyn       6687.57
2         3  Brooklyn       6551.14
0         1    Queens       5922.35
1         2    Queens       5487.73

  sale_weekday  sale_id
3       Sunday      242
2     Saturday      206
6    Wednesday      128
5      Tuesday      116
1       Monday      113
0       Friday       98
4     Thursday       97

    sale_hour  sale_id
0           8       24
1           9       34
2          10       56
3          11       64
4          12       81
5          13       73
6          14       54
7          15       83
8          16       92
9          17      106
10         18      136
11         19      122
12         20       75

    category_name  quantity_sold
1       Beverages            878
11         Snacks            816
9         Produce            787
2           Dairy            702
0          Bakery            528
7          Pantry            481
4          Frozen            420
3            Deli            332
6            Meat            278
5       Household            132
8   Personal Care            130
10        Seafood             89

## 3. Load step

The lecture shows a normal Python to PostgreSQL workflow:
- connect
- execute SQL
- commit
- fetch
- close

For this project, we will load all tables to PostgreSQL in dependency order.  
This is important because parent tables must be loaded before child tables that reference them.

In [30]:
# load order based on your relational dependencies
load_order = [
    "store",
    "department",
    "product_category",
    "vendor",
    "customer",
    "product",
    "employee",
    "vendor_product",
    "store_department",
    "inventory",
    "purchase_order",
    "purchase_order_line",
    "delivery",
    "sales_transaction",
    "sales_transaction_line",
    "payment",
    "customer_loyalty_account",
    "shift_schedule",
    "payroll_record",
    "accounting_record",
]

load_order

['store',
 'department',
 'product_category',
 'vendor',
 'customer',
 'product',
 'employee',
 'vendor_product',
 'store_department',
 'inventory',
 'purchase_order',
 'purchase_order_line',
 'delivery',
 'sales_transaction',
 'sales_transaction_line',
 'payment',
 'customer_loyalty_account',
 'shift_schedule',
 'payroll_record',
 'accounting_record']

### 3.1 Load tables into PostgreSQL

This uses `to_sql` for a practical analyst workflow.
If the tables already exist in PostgreSQL, use `append`.

In [32]:
for table_name in load_order:
    df = tables[table_name].copy()
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists="append",   # change to "replace" only if want pandas to rebuild the table
        index=False,
        method="multi",
        chunksize=1000
    )
    print(f"Loaded {table_name}: {len(df)} rows")

print("Load step finished.")

Loaded store: 5 rows
Loaded department: 7 rows
Loaded product_category: 12 rows
Loaded vendor: 20 rows
Loaded customer: 200 rows
Loaded product: 150 rows
Loaded employee: 75 rows
Loaded vendor_product: 250 rows
Loaded store_department: 35 rows
Loaded inventory: 750 rows
Loaded purchase_order: 100 rows
Loaded purchase_order_line: 300 rows
Loaded delivery: 90 rows
Loaded sales_transaction: 1000 rows
Loaded sales_transaction_line: 3000 rows
Loaded payment: 1000 rows
Loaded customer_loyalty_account: 160 rows
Loaded shift_schedule: 450 rows
Loaded payroll_record: 150 rows
Loaded accounting_record: 1100 rows
Load step finished.

## 4. Validate in PostgreSQL with SQL

In [33]:
def sql_to_df(query):
    with engine.connect() as conn:
        return pd.read_sql(text(query), conn)

In [34]:
# row counts after load
sql_counts = []
for table_name in load_order:
    q = f"SELECT COUNT(*) AS row_count FROM {table_name}"
    result = sql_to_df(q)
    sql_counts.append({
        "table_name": table_name,
        "loaded_row_count": int(result.iloc[0, 0])
    })

sql_counts_df = pd.DataFrame(sql_counts)
sql_counts_df

                  table_name  loaded_row_count
0                      store                 5
1                 department                 7
2           product_category                12
3                     vendor                20
4                   customer               200
5                    product               150
6                   employee                75
7             vendor_product               250
8           store_department                35
9                  inventory               750
10            purchase_order               100
11       purchase_order_line               300
12                  delivery                90
13         sales_transaction              1000
14    sales_transaction_line              3000
15                   payment              1000
16  customer_loyalty_account               160
17            shift_schedule               450
18            payroll_record               150
19         accounting_record              1100

In [35]:
# validation query 1: revenue by store
q1 = '''
SELECT
    s.store_id,
    s.store_name,
    s.borough,
    ROUND(SUM(t.total_amount)::numeric, 2) AS total_revenue
FROM sales_transaction t
JOIN store s
    ON t.store_id = s.store_id
GROUP BY s.store_id, s.store_name, s.borough
ORDER BY total_revenue DESC;
'''

sql_to_df(q1)

   store_id       store_name   borough  total_revenue
0         5  ABC Foodmart B5  Brooklyn        7695.18
1         4  ABC Foodmart B4  Brooklyn        6687.57
2         3  ABC Foodmart B3  Brooklyn        6551.14
3         1  ABC Foodmart Q1    Queens        5922.35
4         2  ABC Foodmart Q2    Queens        5487.73

In [36]:
# validation query 2: transaction pattern by weekday
q2 = '''
SELECT
    TO_CHAR(sale_timestamp, 'Day') AS weekday_name,
    COUNT(*) AS transaction_count
FROM sales_transaction
GROUP BY TO_CHAR(sale_timestamp, 'Day')
ORDER BY transaction_count DESC;
'''

sql_to_df(q2)

  weekday_name  transaction_count
0    Sunday                   242
1    Saturday                 206
2    Wednesday                128
3    Tuesday                  116
4    Monday                   113
5    Friday                    98
6    Thursday                  97

In [37]:
# validation query 3: quantity sold by category
q3 = '''
SELECT
    pc.category_name,
    SUM(stl.quantity_sold) AS total_quantity_sold
FROM sales_transaction_line stl
JOIN product p
    ON stl.product_id = p.product_id
JOIN product_category pc
    ON p.category_id = pc.category_id
GROUP BY pc.category_name
ORDER BY total_quantity_sold DESC;
'''

sql_to_df(q3)

    category_name  total_quantity_sold
0       Beverages                878.0
1          Snacks                816.0
2         Produce                787.0
3           Dairy                702.0
4          Bakery                528.0
5          Pantry                481.0
6          Frozen                420.0
7            Deli                332.0
8            Meat                278.0
9       Household                132.0
10  Personal Care                130.0
11        Seafood                 89.0

In [38]:
# validation query 4: low stock products
q4 = '''
SELECT
    i.store_id,
    i.product_id,
    i.quantity_on_hand,
    i.reorder_level
FROM inventory i
WHERE i.quantity_on_hand < i.reorder_level
ORDER BY i.store_id, i.product_id;
'''

sql_to_df(q4)

   store_id  product_id  quantity_on_hand  reorder_level
0         3         146                 4              5
1         4           5                 4              5
2         4          49                 0              5

In [39]:
# validation query 5: loyalty status counts
q5 = '''
SELECT
    account_status,
    COUNT(*) AS account_count
FROM customer_loyalty_account
GROUP BY account_status
ORDER BY account_count DESC;
'''

sql_to_df(q5)

  account_status  account_count
0         active            143
1       inactive             17

## 7. Final ETL summary

This notebook shows a full ETL workflow for the ABC Foodmart project:

### Extract
- read generated CSV files into pandas

### Transform
- convert dates and timestamps
- check duplicates and missing values
- validate PK and FK logic
- apply business rule checks
- create analysis-ready fields for BI

### Load
- load normalized tables into PostgreSQL in dependency order

### Validate
- run SQL checks from Python
- confirm row counts and business summaries
- confirm the database is ready for analyst SQL and Metabase dashboards